title: Hello, world! I'm myWork
description: 
permalink: ':title/'
baseurl: /mywork-faq # the subpath of your site, e.g. /blog
url: https://github.com/napit-apps # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 'myWork - Tipps & Tricks' # add your name
author-img: myWork.png # add your photo
about-author: 'Hier findest du viele nützliche Tipps die dir das Leben leichter machen werden. <br />Gerne helfe ich dir auch persönlich weiter.'
social-email: 'sag.hallo@marcelruss.de' # add your Email address
social-page: 'https://marcelruss.de'

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
